### ISSUE TITLE
Search option does not work in the portal

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#104]
I have tried to search name in the Tree and in the Search. Neither is working:

![image](https://user-images.githubusercontent.com/28574252/102098499-e9dbbb80-3dec-11eb-926a-78dd8d1bd457.png)

![image](https://user-images.githubusercontent.com/28574252/102098434-d4ff2800-3dec-11eb-8c2e-47bb856d2ad6.png)

**Comment by mdoering** [comment]
see chat
