### ISSUE TITLE
References are missing with synonyms on species page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#105]
Feedback from Paul Schoolmeesters: 

>I regret that the original reference for a species is not used when there has been any modification, in which case the last reference is shown.
The example Ammoecioides catulus (Balthasar, 1946)
In 2019 reference is correct (in the book picture)
Best wishes, Paul Schoolmeesters

**Comment by yroskov** [comment]
Indeed, references are missing with synonyms/combinations. Paul meant, original combination had no reference in a new portal.

![image](https://user-images.githubusercontent.com/28574252/102126583-e1957780-3e10-11eb-82cd-1fd63da7e3a0.png)

However, this references is present in the clearinghouse. Aphodius (Ammoecius) catulus Balthasar, 1946, a synonym (original combination) of accepted name Ammoecioides catulus (Balthasar, 1946) has reference  Balthasar V. De novis generis Aphodius speciebus. Acta entomologica Musei nationalis Pragae 24(310):53-68. (1946).

Clearinghouse has this reference here:
https://data.catalogueoflife.org/dataset/1027/name/OC-01-.01-.01-.00-.025-.000-.012-.-

**Comment by mdoering** [comment]
Indeed. This is also [not shown in ChecklistBank](https://github.com/CatalogueOfLife/checklistbank/issues/781), only in the name details page (which I think we should avoid using, but rather integrate more information into the main taxon page).
