### ISSUE TITLE
GetReleaseMetadata overwrites preview datasetKey

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/portal#106]
https://github.com/CatalogueOfLife/portal/blob/0ed53c6b7512b2d599ba42f551041ade4ec6c6ce/_plugins/get_release_metadata.rb#L32

**Comment by yroskov** [comment]
It looks like new release to the preview site failed. Checklist data and metadata at https://preview.catalogueoflife.org belong to old version of 2020-12-01.

**Comment by thomasstjerne** [comment]
This seems to work after a fresh build, closing
