### ISSUE TITLE
Batch name matching tool

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#11]
to replace http://www.catalogueoflife.org/listmatching/
similar to the current GBIF one: https://www.gbif.org/tools/species-lookup

**Comment by thomasstjerne** [comment]
@mdoering  please provide relevant endpoints and examples as comments on this issue

**Comment by mdoering** [comment]
To do sth like the gbif tool we need to do 2 steps for each name in the Clearinghouse:

1) match the input name to the names index
2) lookup full name usage in the target dataset using the names index id from 1

1)
```
GET https://api.catalogue.life/name/matching?q=Isurus%20paucus&rank=species&code=zoological&verbose=true"

{
  "name": {
    "created": "2019-11-21T14:28:35.887184",
    "createdBy": 11,
    "modified": "2019-11-21T14:28:35.887184",
    "modifiedBy": 11,
    "datasetKey": 1,
    "id": "4B4ZR",
    "homotypicNameId": "4B4ZR",
    "scientificName": "Isurus paucus",
    "rank": "species",
    "genus": "Isurus",
    "specificEpithet": "paucus",
    "candidatus": false,
    "combinationAuthorship": {
      "authors": [
        "Guitart"
      ],
      "year": "1966"
    },
    "code": "zoological",
    "nomStatus": "doubtful",
    "origin": "name matching",
    "type": "scientific",
    "parsed": true,
    "formattedName": "<i>Isurus</i> <i>paucus</i> Guitart, 1966"
  },
  "type": "variant"
}
```

The returned `"id": "4B4ZR"` is the names index id.
Then call the search with your target datasetKey (to be selected by the user, default to 3?):

```
GET https://api.catalogue.life/dataset/3/nameusage/search?NAME_INDEX_ID=4CUGR"
```

This now returns full name usages as the regular search does.
Incl the accepted for synonyms and the entire classification.

Note that a) there can be a No match in step 1 and b) there can be multiple names returned in step 2! The example above returns both an accepted name and a misapplied name.

The tool should show both (or more) and also include them in the CSV - guess the simplest is to duplicate the returned row for each match?
