### ISSUE TITLE
Change label in the interface as "Synonyms & Combinations"

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#121]
Please change label on Species page from "Synonyms" to "**Synonyms & Combinations**".

Reason: zoologists are uncomfortable with old name.

https://www.catalogueoflife.org/data/taxon/3YLJ4

![image](https://user-images.githubusercontent.com/28574252/107810542-78f44980-6d32-11eb-8b30-3d7452ec4fb4.png)

**Comment by mdoering** [comment]
@dhobern @chantalhuijbers do we need to discuss this in a wider audience?
The old portal called it also just synonyms for decades without a complaint. So does DwC, TCS, GBIF, WoRMS and ITIS to my knowledge.

<img width="537" alt="Screenshot 2021-02-13 at 07 48 58" src="https://user-images.githubusercontent.com/327505/107844021-426d0c00-6dd0-11eb-84aa-4a147f938ce0.png">

I am not in favor of changing it, but If we would do it should also impact ColDP and API terminology? That would be a rather serious impact.

**Comment by yroskov** [comment]
> The old portal called it also just synonyms for decades without a complaint.

It is not true. Through all these decades, CoL was criticized for including combinations in “synonyms” (botanical style). Such practice contradicts ICZN and zoological taxonomy.

Recently, a new schema and interface is also criticized for use of botanical term “basionym” for original combinations.

Well, if we compare number of “botanical names” vs “zoological names”, you quickly understand which practice have right to dictate the vocabulary.
