### ISSUE TITLE
Metadata: formatting problems

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#123]
https://preview.catalogueoflife.org/data/metadata

Dataset: CoL of 2021-02-16.

Incorrect presentation of headings with double hashes. How to fix this? @thomasstjerne 

"##" Editors Editors of the COL Checklist are:
"##" Organisations 
"##" Recommended citation 
"##" Data Downloads

![image](https://user-images.githubusercontent.com/28574252/108221057-fdf9ad00-70fc-11eb-9467-6fa72e8861f3.png)

![image](https://user-images.githubusercontent.com/28574252/108221089-07831500-70fd-11eb-9ede-3db31c208283.png)

**Comment by thomasstjerne** [comment]
Odd, it looks fine here.

But on your screenshot it looks like the markdown has been wrongly parsed

**Comment by yroskov** [comment]
@gdower has fixed my mistakes and teached me to use right markdown tags

**Comment by yroskov** [comment]
All are fine now

**Comment by mdoering** [comment]
There are many online markdown editors if you need to write/test something:
https://stackedit.io
