### ISSUE TITLE
Add bioschemas.org markup to taxon pages

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#126]
**What feature are we missing?**
...

At the TDWG Bioschemas webinar, people were asking if CoL could add [bioschemas.org](https://bioschemas.org) to CoL taxon pages. 

Example deployments can be seen here:

https://bioschemas.org/liveDeploys/

**Comment by mdoering** [comment]
@thomasstjerne @MattBlissett 
you seem to have discussed early ideas how to do this with the dynamic React components. How can we inject html snippets into the React DOM? Could the Java backend serve these?

**Comment by mdoering** [comment]
Possible freemarker template for the backend with Open Graph, Twitter cards and schema.org LD:

```
<meta property="og:title" content="${info.taxon.getLabel()}" />
<meta property="og:url" content="https://www.catalogueoflife.org/data/taxon/${info.taxon.getId()}" />
<meta property="og:description" content="${info.taxon.label} in the Catalogue of Life" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content="@catalogueoflife"/>
<meta name="twitter:title" content="${info.taxon.label}" />
<meta name="twitter:description" content="${info.taxon.label} in the Catalogue of Life" />
<meta name="twitter:image" content="https://www.catalogueoflife.org/images/col_square_logo.jpg" />

<script type="application/ld+json">
{
  "@context": [
    "https://schema.org/",
    {
      "dwc": "http://rs.tdwg.org/dwc/terms/",
      "col": "http://catalogueoflife.org/terms/",
      "dwc:vernacularName": {
        "@container": "@language"
      }
    }
  ],
  "@type": "Taxon",
  "additionalType": [
    "dwc:Taxon",
    "http://rs.tdwg.org/ontology/voc/TaxonConcept#TaxonConcept"
  ],
  "identifier": [
    {
      "@type": "PropertyValue",
      "name": "dwc:taxonID",
      "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
      "value": "${info.taxon.getId()}"
    },
    {
      "@type": "PropertyValue",
      "name": "col:ID",
      "propertyID": "http://catalogueoflife.org/terms/ID",
      "value": "${info.taxon.getId()}"
    }
  ],
  "name": "${info.taxon.label}",
  "scientificName": {
    "@type": "TaxonName",
    "name": "${info.taxon.name.scientificName!}",
    "author": "${info.taxon.name.authorship!}",
    "taxonRank": "${info.taxon.name.rank!}",
  <#if info.getPublishedInReference()??>
    "isBasedOn": {
      "@type": "ScholarlyArticle",
      "name": "${info.getPublishedInReference().citation!}"
    }
  </#if>
  },
  <#if info.taxon.name.rank??>
  "taxonRank": [
    "http://api.catalogueoflife.org/vocab/rank/${info.taxon.name.rank}",
    "${info.taxon.name.rank}"
  ],
  </#if>

<#if info.synonyms??>
  "alternateName": [
     <#list info.synonyms as s>
      "${s.label}",
     </#list>
  ],
  "alternateScientificName": [
    <#list info.synonyms as s>
    {
      "@type": "TaxonName",
      "name": "${s.name.scientificName}",
      "author": "${s.name.authorship}",
      "taxonRank": "${s.name.rank}"
      <#if s.name.publishedInId??>
       ,"isBasedOn": {
          "@type": "ScholarlyArticle",
          "name": "${info.getReference(s.name.publishedInId).citation!}"
        }
      </#if>
    },
    </#list>
  ],
</#if>

<#if info.vernacularNames??>
  <#list info.vernacularNames as v>
  "dwc:vernacularName": [
    {
      "@language": "${v.language!}",
      "@value": "${v.name!}"
    },
  </#list>
  ],
</#if>

<#if parent??>
  "parentTaxon": {
    "@type": "Taxon",
    "name": "${parent.label!}",
    "scientificName": {
      "@type": "TaxonName",
      "name": "${parent.name!}",
      "author": "${parent.authorship!}",
      "taxonRank": "${parent.rank!}"
    },
    "identifier": [
      {
        "@type": "PropertyValue",
        "name": "dwc:taxonID",
        "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
        "value": "${parent.id}"
      },
      {
        "@type": "PropertyValue",
        "name": "col:ID",
        "propertyID": "http://catalogueoflife.org/terms/ID",
        "value": "${parent.id}"
      }
    ],
    "taxonRank": [
      "http://rs.gbif.org/vocabulary/gbif/rank/${parent.rank}",
      "${parent.rank}"
    ]
  }
</#if>

}
</script>
```

**Comment by thomasstjerne** [comment]
Also add 
`<meta property="og:image"  content="https://www.catalogueoflife.org/images/col_square_logo.jpg" />
`

**Comment by mdoering** [comment]
available on dev now: http://api.dev.catalogueoflife.org/dataset/3LR/taxon/B3SX/portalheader

**Comment by mdoering** [comment]
@MattBlissett did you already find a way to include html snippets in apache?

**Comment by MattBlissett** [comment]
I don't think this can be done with Apache SSI ([Server Side Includes](https://httpd.apache.org/docs/current/mod/mod_include.html#includevirtual)) alone.

Given a file /test8.shtml:

```Test page <pre> <!--#printenv --> </pre>

<!--#include virtual="/data/taxon-bioschema/P" -->

End includ.
```

and Apache configuration:

```
  RequestHeader unset Accept-Encoding
  RewriteRule          ^/data/taxon-bioschema/([^.]+)$ http://api.dev.catalogueoflife.org/dataset/3LR/taxon/$1/portalheader [proxy]

  # Existing line in the config
  RewriteRule          ^/[^.]+$ /var/www/html/col-portal/index.html

  <Directory /var/www/html/col-portal>
    Options +Includes
  </Directory>
```

the result includes the metadata for taxon P, but there is no way I can see to include `/data/taxon-bioschema/${DOCUMENT_PATH_INFO}`

Instead, there would need to be a CGI script (Python, Perl, PHP, Ruby, C++, whatever) which the `virtual` call could point to.  That can read `${DOCUMENT_PATH_INFO}`. The usual requirements on parsing user data (the URL) apply.

(So a shell script with the line `curl -Ss http://api.dev.catalogueoflife.org/dataset/3LR/taxon/$DOCUMENT_PATH_INFO/portalheader` might work, except that's a terrible idea for security.)

Of course, the site is no longer a static site with something like this.

**Comment by MattBlissett** [comment]
I have left the Apache HTTPD configuration in the file, but commented out. test8.shtml also exists, although the next deployment should delete it.

**Comment by thomasstjerne** [comment]
Maybe sth like this https://stackoverflow.com/questions/17929632/processing-external-page-with-perl-cgi-or-act-as-a-reverse-proxy

**Comment by MattBlissett** [comment]
Yes, exactly.  For something this simple, Perl is fine — and has the advantage that there's presumably a CentOS package for the Perl CGI module.

**Comment by mdoering** [comment]
If we run a CGI to include metadata from the java backend - are the entire taxon pages then not better served directly from the backend instead of running 2 processes?

**Comment by thomasstjerne** [comment]
That would require the backend to pickup the html pages as generated by Jekyll to render menus properly and pickup changes (main menu, react component versions, etc).

**Comment by mdoering** [comment]
Yes, that'll be really silly. But it looks to me that the SSI include directive should be able to use the PATH variables. The identifiers needs to be parsed out, but otherwise should this not work?

**Comment by mdoering** [comment]
It just needs AcceptPathInfo On

**Comment by mdoering** [comment]
Got it to work with SSI only, comitted to http configs: https://github.com/CatalogueOfLife/deploy/blob/master/configs/dev/virt_www.catalogueoflife.org.conf

But not to the jekyll pages as it interfers with the Jekyll SEO tag
It needs this:

```
<!--#if expr='v("REQUEST_URI") =~ m#data/taxon/(.+)# && $1 =~ /(.*)/' -->
    <!--#set var="ID" value="$0" -->
    <!--#include virtual="/_taxonheader/${ID}" -->
<!--#else -->
  <meta property="og:title" content="Taxon" />
  <meta name="description" content="The Catalogue of Life" />
  <meta property="og:description" content="The Catalogue of Life" />
  <script type="application/ld+json">
{"description":"The Catalogue of Life","@type":"WebPage","url":"/data/taxon","headline":"Taxon","@context":"https://schema.org"}
  </script>
<!--#endif -->
```

**Comment by mdoering** [comment]
got it working with SSI and the jekyll SEO plugin which can now be turned off in the default layout via a new `seo_ssi: true` variable. Gonna do the same for datasets too.
