### ISSUE TITLE
COL logo has wrong homepage link

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#133]
The square logo for COL in the footer (the four-coloured block) does not link to the homepage for all pages with a path, e.g. https://www.catalogueoflife.org/data/index.html or https://www.catalogueoflife.org/about/catalogueoflife is broken.

**Comment by mdoering** [comment]
@gdower did you solve this already?

**Comment by gdower** [comment]
Fixed https://github.com/CatalogueOfLife/portal/commit/08ac34596b79ffe53d169262677ce104a6f7fa7e
