### ISSUE TITLE
Show DOIs and document how to use

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#137]
Once we have DOIs for COL and its sources we want to show them nicely in the portal and advertise their use and how to cite COL. We also need some documentation on how we version them, i.e. we create new DOIs for every COL release with all its sources. There should also be a single DOI for the latest version of the COL alone, but not for the sources as these potentially change with every release.

**Comment by mdoering** [comment]
can this be closed now?

**Comment by mdoering** [comment]
I have added the DOI as a link to the footer, metadata page and all release posts on [dev](https://www.dev.catalogueoflife.org/data/metadata).
@chantalhuijbers @thomasstjerne should make those prettier or is this good enough?

**Comment by chantalhuijbers** [comment]
I think this is great Markus! Please leave this ticket open, I am planning to put up the FAQ page, that has been in draft for way too long, soon and will include some info about the DOIs to that. Will assign ticket to myself.
