### ISSUE TITLE
Decide on stable portal URLs for releases

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#139]
The primary URL a COL release points to cannot be the main COL portal as this changes with every release.
We need a stable URL for a specific version. Ultimately this can only be ChecklistBank.

But I would propose to create a stable URL in the main portal, similar to how we dealt with the previous annual releases, that can either forward redirect directly to ChecklistBank. Stable URLs would then only need to be managed for the portal and give us freedom to change the much more complex CLB application as seems useful. We could then also easily host tombstone pages for monthly releases that have been removed from ChecklistBank. And maybe better integrate also release notes such as https://preview.catalogueoflife.org/2021/04/05/release

We could consider to continue with the previous scheme for annual releases:
https://www.catalogueoflife.org/annual-checklist/2021

... and do sth similar for the monthly ones:
https://www.catalogueoflife.org/monthly-checklist/2021-04

But maybe it is better to use a new structure like this which does not differ between annual and monthly when the only difference between them really is the longevity of the data:
https://www.catalogueoflife.org/release/2021-04
https://www.catalogueoflife.org/checklist/2021-04

Instead of doing release notes as news items I would consider to have dedicated release pages that populate those above URLs

**Comment by timrobertson100** [comment]
If the intent is for people, I suggest using the DOI as the stable URL as it allows you to change the target of resolution.

If the intent is for scripts, then they add complexity as you need to unpack DOI metadata to extract the `url` property e.g. [this large example](https://api.datacite.org/dois/10.15468/dl.79tfrn)

**Comment by mdoering** [comment]
Right, I was thinking in circles. The intend of these URLs was to be used for resolving the DOI, to be part of the DOI metadata. But the registered DOI URL can change in case we change ChecklistBanks URL layout, so there is no need to provide extremely stable URLs otherwise - the DOI is exactly for that. 

And we can even change the DOI metadata for subsequent releases so that when we issue a new release DOI we can point to the main portal, but when we issue another release the previous one gets changed to now link to ChecklistBank.
