### ISSUE TITLE
All English_names_of_the_group are missing

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#149]
Preview website, the list of Source_Datasets: https://preview.catalogueoflife.org/data/source-datasets

CoL 2021-07-06

**All English Names of the Group are missing:**

![image](https://user-images.githubusercontent.com/28574252/124975349-8d8ff180-dff3-11eb-8052-e854840c5e57.png)

**Comment by mdoering** [comment]
Should we also rename the column title from "English Names of the Group" to sth simpler, e.g. "Coverage" ?

**Comment by chantalhuijbers** [comment]
I agree with renaming to Coverage or as it is called in the metadata 'Taxonomic coverage'.
