### ISSUE TITLE
Migrate static pages

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#16]
Migrate and partly rewrite static pages from:

 - [ ] http://www.catalogueoflife.org
 - [ ] https://species2000.org

See also https://github.com/CatalogueOfLife/general/issues/70

**Comment by dhobern** [comment]
Thanks @mdoering - I've been working on preparing this externally from Github. Should I aim in the end to check content into Github?

**Comment by dhobern** [comment]
@olafbanki - to what extent do we want to present Species 2000 as a central entity on the new site? Are we shifting across completely to CoL?

**Comment by mdoering** [comment]
@dhobern yes, the content all needs to go into this repository as markup files.
And I would argue the sooner the better so we can show progress at https://www.catalogue.life and get early feedback. There is no need to get it all right and covered in the beginning. Every little improvement is an improvement to what we got now.

**Comment by dhobern** [comment]
I've been working on this - I think we treat release one as a beta for user feedback on the content and presentation and that we avoid unnecessary content migration for now.

**Comment by mdoering** [comment]
can we break it down into individual issues and close this one?

**Comment by dhobern** [comment]
I think we first need to make a definitive list of what we need to add to the new site and where it comes from. Once we have that, we should split it into different issues.

Maybe we can use this issue to capture the remaining content we want to add in. @olafbanki ?
