### ISSUE TITLE
sitemap-XX.txt urls are incorrect for species pages

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#166]
The decline in search engine page rank @yroskov raised in the Global Team meeting might be from the URLs being incorrect in the sitemap-XX.txt files:

https://www.catalogueoflife.org/sitemap-ba.txt
```
https://www.catalogueoflife.org/taxon/3GUJ3
https://www.catalogueoflife.org/taxon/3GUHW
https://www.catalogueoflife.org/taxon/3GUJM
https://www.catalogueoflife.org/taxon/3GUJS
```

Should be:
```
https://www.catalogueoflife.org/data/taxon/3GUJ3
https://www.catalogueoflife.org/data/taxon/3GUHW
https://www.catalogueoflife.org/data/taxon/3GUJM
https://www.catalogueoflife.org/data/taxon/3GUJS
```

Even with the directory corrected, some of the URLs are also returning 404's which probably could also penalize page rank:

https://www.catalogueoflife.org/data/taxon/3GUJ3

**Comment by mdoering** [comment]
Thanks, the bad URLs can be fixed quickly as a start.
We have never updated the sitemaps since we first released stable ids in december, so that is sth we should do soon. And at least with every annual release.

**Comment by mdoering** [comment]
See also https://github.com/CatalogueOfLife/portal/issues/165

**Comment by mdoering** [comment]
deployed to prod
