### ISSUE TITLE
404 handling on taxon pages

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#169]
**Describe the bug**
There are a few issues with the 404 handling on the portal, including that the overall HTTP status code for non-existent taxon pages returned is a 200, not a 404. An output message probably put there for debugging purposes also gets printed at the top of the page. I think the lack of a 404 error might [penalize SEO](https://github.com/CatalogueOfLife/portal/issues/165) because it will result in a lot of duplicate pages with the same exact "404" content, but the search engine crawler won't know it's a 404 error.

Regenerating the sitemap on deployment becomes even more important if we can't return a 404 status code.

**To Reproduce**
1. Go to https://www.catalogueoflife.org/data/taxon/3GUJ3
2. Look at the status codes returned
3. Check the banner

**Screenshots**
![image](https://user-images.githubusercontent.com/8573609/143294548-8ed1d35b-ae3e-48de-8720-c36d118b1fd1.png)

**Browser:**
 - OS: Linux
 - Browser: Firefox

**Comment by gdower** [comment]
@mdoering, I tested the top 1000 IDs in the sitemap_ba.txt file for the https://api.catalogueoflife.org/dataset/3LR/taxon/ endpoint and got 404 errors for 37%. Can the sitemap files be regenerated on deployment? I could open a separate issue for that.

**Comment by mdoering** [comment]
They were created rather manually then. We should create them when a release goes public I reckon?

**Comment by mdoering** [comment]
37% is a lot. We should investigate why that is.

**Comment by gdower** [comment]
The portal also calls the https://api.catalogueoflife.org/dataset/3LR/synonym/ endpoint and that always returned a 404 for the top 1000 IDs, but maybe that's just an artifact of taking the IDs from the sitemap?

**Comment by mdoering** [comment]
no idea, @thomasstjerne it seems the portal always calls taxon, taxon/info and synonym for any ID?

**Comment by mdoering** [comment]
portal now returns 404 status codes and a new Dodo 404 page: https://www.catalogueoflife.org/data/taxon/Dodo
