### ISSUE TITLE
Server rewrite rules

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/portal#17]
When deploying on Netlify, this line in the `_redirects` file was needed for Taxon pages to load properly:

`/data/taxon/*   /data/taxon/    200
`

We need similar rewriting (mod_rewrite stuff in Apache I think) to achieve this.
And also for datasets

`/data/dataset/*   /data/dataset/    200
`

**Comment by MattBlissett** [comment]
Since that's private: 

```
        AliasMatch ^/data/dataset/[^.]+$ /var/www/html/col-portal/data/dataset.html
        AliasMatch ^/data/taxon/[^.]+$ /var/www/html/col-portal/data/taxon.html
        AliasMatch ^/[^.]+$ /var/www/html/col-portal/index.html
```
