### ISSUE TITLE
Update robots.txt on www.dev and preview

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#170]
**Describe the bug**
The current robots.txt on `www.dev` and `preview` is allowing search engines to index those non-public domains. We should block it from being indexed:

```
User-agent: *
Disallow: /
```

Indexing those subdomains probably [penalizes our SEO](https://github.com/CatalogueOfLife/portal/issues/165) from duplicate content:

![image](https://user-images.githubusercontent.com/8573609/143314641-0e1ac0e3-cdfa-4400-bcf0-51e7b6533204.png)

Based on the current configuration of the dev and preview robots.txt files, I'm not really sure why it is getting indexed, unless @mdoering fixed it with the fc9d2606e013b9539359db0148c123f6f79f88d8 commit.

https://www.dev.catalogueoflife.org/sitemap-ba.txt

It would probably be preferable to completely block the search engines on the `www.dev` and `preview` subdomains.

**Comment by mdoering** [comment]
made robots.txt environment specific and deployed dev & preview
