### ISSUE TITLE
Reduce redundant API calls

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#172]
When a dynamic data page (taxon or dataset) is rendered in the portal we request the same data twice.
Once within the API call that renders the original html which includes SEO friendly metadata.
And then once again when the React component renders the main layout.

As most of the data is already known when the API builds the page, could the React components try to fetch data from an inline JSON object that is part of the html and only call the API when that does not exist, e.g. when used outside of the portal?

**Comment by thomasstjerne** [comment]
As these components are made to be unaware of their surrounding app / page (i.e. to be useful on other websites), I am not very keen on introducing this complexity. It will make the code harder to maintain and debug in the long run.
