### ISSUE TITLE
Preview website: statistics and lists are not shown

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#173]
https://preview.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&sortBy=taxonomic

For attention of @thomasstjerne and @mdoering 

I need to see lists and statistics for accepted species, ifraspecific taxa and synonyms on Search the Catalogue page, as it was done before. This time, I have empty forms in Ranks and Status boxes:

![image](https://user-images.githubusercontent.com/28574252/146051759-13db519c-178f-47e2-a043-c4caeec738a3.png)

Expected behavior (as on prod):

![image](https://user-images.githubusercontent.com/28574252/146052015-0b6d227c-6fae-4e61-ad77-6b3944c74c8b.png)

**Comment by yroskov** [comment]
Well, no one search option works in PREVIEW:

![image](https://user-images.githubusercontent.com/28574252/146068822-9aedeb82-9ddb-4535-afac-9462a01b340a.png)

**Comment by mdoering** [comment]
the search index is empty. You did a release on the 13th when we had huge problems with the installation and had to restart the API in an emergency twice. Basically the release never completed, please delete it and do another one!

**Comment by yroskov** [comment]
Another PREVIEW release of 2021-12-14:

- [ ] Search still does not work in PREVIEW:
![image](https://user-images.githubusercontent.com/28574252/146221853-c045544c-7203-441c-97cd-36ef47d0a899.png)
![image](https://user-images.githubusercontent.com/28574252/146221960-f2fa7330-323c-4cb2-bc4b-c646beffa034.png)

**Comment by yroskov** [comment]
Oh, OK. Thanks!

As for me, all GSDs updated as expected. December edition is closed. Remaining problems: incomplete references is some GSDs.

**Comment by mdoering** [comment]
there is an issue with the release code. I dont think I changed it, but it uses up all database connections so I had to kill the job again. Will work on a fix and then do a release again. Sorry for the inconvenience!

**Comment by yroskov** [comment]
We still have a time before Christmas :)
