### ISSUE TITLE
Portal: Error 500 for taxon page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#182]
Paul Schoolmeesters 2022-03-28 reported:
>This message received when going to species details
{"code":500,"message":"There was an error processing your request. It has been logged (ID 24596966fbf99216)."}
What is the problem
Kind regards Paul Schoolmeesters

Indeed, search for tribe Scarabaeini opens a Tree, but click on a tribe, or on a genus, or on a species gives error 500:
![image](https://user-images.githubusercontent.com/28574252/160402666-f4ed1d65-b2b6-4ed2-9710-59781f2de608.png)
 
Search for the species Trifolium ambiggum gives a page with error 500:
https://www.catalogueoflife.org/data/taxon/58PN6
![image](https://user-images.githubusercontent.com/28574252/160402184-86178174-5f7e-4f0d-bb8f-bbfb658deb45.png)

_Conclusion:_ 
**Taxon page is not accessible.**

**Comment by timrobertson100** [comment]
@mdoering has applied a temporary fix as an interim solution
