### ISSUE TITLE
Add @id to embedded JSON-LD so it is usable by RDF aggregators

### ISSUE THREAD

**Issue by rdmpage** [CatalogueOfLife/portal#185]
TL;TR COL JSON-LD should have @id statements for the taxon and its parent taxon

It's great to see RDF in COL, but it's not quite ready for consumption by triple stores. Ideally each "thing" should have a unique identifier, and that identifier is in the RDF. At the moment COL does not include any `@id` statements.  For example, for https://www.catalogueoflife.org/data/taxon/35CN6 the JSON-LD looks like this:

<details>
  <summary>
    JSON-LD for 35CN6 (click to see)
  </summary>
<pre>
{
  "@context": [
    "https://schema.org/",
    {
      "dwc": "http://rs.tdwg.org/dwc/terms/",
      "col": "http://catalogueoflife.org/terms/"
    }
  ],
  "@type": "Taxon",
  "additionalType": [
    "dwc:Taxon",
    "http://rs.tdwg.org/ontology/voc/TaxonConcept#TaxonConcept"
  ],
  "identifier": [
    {
      "@type": "PropertyValue",
      "name": "dwc:taxonID",
      "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
      "value": "35CN6"
    },
    {
      "@type": "PropertyValue",
      "name": "col:ID",
      "propertyID": "http://catalogueoflife.org/terms/ID",
      "value": "35CN6"
    }
  ],
  "name": "Diaporthe acaciigena Crous, Pascoe &amp; Jacq. Edwards",
  "scientificName": {
    "@type": "TaxonName",
    "name": "Diaporthe acaciigena",
    "author": "Crous, Pascoe &amp; Jacq. Edwards",
    "taxonRank": "Species"
    ,"isBasedOn": {
      "@type": "ScholarlyArticle",
      "name": "Crous, Pascoe &amp; Jacq. Edwards. In: in Crous, Groenewald, Shivas, Edwards, Seifert, Alfenas, Alfenas, Burgess, Carnegie, Hardy, Hiscock &amp; Hübe, Persoonia 26: 123. (2011)."
    }
  },
  "taxonRank": [
    "https://api.checklistbank.org/vocab/rank/Species",
    "Species"
  ],
  "alternateName": [
  ],
  "alternateScientificName": [
  ],
  "parentTaxon": {
    "@type": "Taxon",
    "name": "Diaporthe",
    "scientificName": {
      "@type": "TaxonName",
      "name": "Diaporthe",
      "author": "",
      "taxonRank": "Genus"
    },
    "identifier": [
      {
        "@type": "PropertyValue",
        "name": "dwc:taxonID",
        "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
        "value": "62PCP"
      },
      {
        "@type": "PropertyValue",
        "name": "col:ID",
        "propertyID": "http://catalogueoflife.org/terms/ID",
        "value": "62PCP"
      }
    ],
    "taxonRank": [
      "http://rs.gbif.org/vocabulary/gbif/rank/Genus",
      "Genus"
    ]
  }
}
</pre>
</details>

If I convert this to triples I get a flood of b nodes, which isn't what I want. Instead, I should mostly get triples with either `https://www.catalogueoflife.org/data/taxon/35CN6` (the taxon) or `https://www.catalogueoflife.org/data/taxon/62PCP` (its parent) as the subject.

<details>
  <summary>
    JSON-LD for 35CN6 with @id (click to see)
  </summary>
<pre>
{
  "@context": [
    "https://schema.org/",
    {
      "dwc": "http://rs.tdwg.org/dwc/terms/",
      "col": "http://catalogueoflife.org/terms/"
    }
  ],
  "@id":"https://www.catalogueoflife.org/data/taxon/35CN6",
  "@type": "Taxon",
  "additionalType": [
    "dwc:Taxon",
    "http://rs.tdwg.org/ontology/voc/TaxonConcept#TaxonConcept"
  ],
  "identifier": [
    {
      "@type": "PropertyValue",
      "name": "dwc:taxonID",
      "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
      "value": "35CN6"
    },
    {
      "@type": "PropertyValue",
      "name": "col:ID",
      "propertyID": "http://catalogueoflife.org/terms/ID",
      "value": "35CN6"
    }
  ],
  "name": "Diaporthe acaciigena Crous, Pascoe &amp; Jacq. Edwards",
  "scientificName": {
    "@type": "TaxonName",
    "name": "Diaporthe acaciigena",
    "author": "Crous, Pascoe &amp; Jacq. Edwards",
    "taxonRank": "Species"
    ,"isBasedOn": {
      "@type": "ScholarlyArticle",
      "name": "Crous, Pascoe &amp; Jacq. Edwards. In: in Crous, Groenewald, Shivas, Edwards, Seifert, Alfenas, Alfenas, Burgess, Carnegie, Hardy, Hiscock &amp; Hübe, Persoonia 26: 123. (2011)."
    }
  },
  "taxonRank": [
    "https://api.checklistbank.org/vocab/rank/Species",
    "Species"
  ],
  "alternateName": [
  ],
  "alternateScientificName": [
  ],
  "parentTaxon": {
    "@id":"https://www.catalogueoflife.org/data/taxon/62PCP",
    "@type": "Taxon",
    "name": "Diaporthe",
    "scientificName": {
      "@type": "TaxonName",
      "name": "Diaporthe",
      "author": "",
      "taxonRank": "Genus"
    },
    "identifier": [
      {
        "@type": "PropertyValue",
        "name": "dwc:taxonID",
        "propertyID": "http://rs.tdwg.org/dwc/terms/taxonID",
        "value": "62PCP"
      },
      {
        "@type": "PropertyValue",
        "name": "col:ID",
        "propertyID": "http://catalogueoflife.org/terms/ID",
        "value": "62PCP"
      }
    ],
    "taxonRank": [
      "http://rs.gbif.org/vocabulary/gbif/rank/Genus",
      "Genus"
    ]
  }
}
</pre>
</details>

This JSON-LD will generate the correct triples such as 
```
<https://www.catalogueoflife.org/data/taxon/35CN6> <http://schema.org/parentTaxon> <https://www.catalogueoflife.org/data/taxon/62PCP> .
```
In an ideal world we would also have `@id` for the `scientificName` and `isBasedOn` (e.g., LSIDs and DOIs, respectively, but I realise that requires some additional mapping between strings and things.

**Comment by mdoering** [comment]
I have added the 2 id statements as you suggested. I am slightly uncomfortable to make the website URL the identifier. But as this is the resource that returns the content I suppose it's correct. I would just not trust in its stability as much as in the pure identifier.

Will be on dev first and when working put into production soon, maybe later today.

**Comment by mdoering** [comment]
@rdmpage does that look good?
https://www.dev.catalogueoflife.org/data/taxon/35CN6

**Comment by mdoering** [comment]
ahhh, the domain is wrong for dev...

**Comment by rdmpage** [comment]
There is an argument that the identifier for the web page and for the taxon shouldn't be the same thing (at the cost of more complexity, my sense is that most embedded JSON-LD doesn't make this distinction, see https://github.com/rdmpage/wild-json-ld for a collection of JSON-LD examples). 

For example @rogerhyam has set up the World Flora Online such that the @id for a taxon is https://list.worldfloraonline.org/wfo-4000000718 (e.g., see https://list.worldfloraonline.org/wfo-4000000718/json ) and the web page is http://www.worldfloraonline.org/taxon/wfo-4000000718. The URLs are clearly similar but are different. One way to model this might be:

```
{
 "@id" : "https://list.worldfloraonline.org/wfo-4000000718",
"mainEntityOfPage" : "http://www.worldfloraonline.org/taxon/wfo-4000000718"
}
```

so that if we get the RDF we can speak about taxa instead of web pages, but preserve the link to the web page itself. But this means you will want to have a service that returns RDF (e.g., https://list.worldfloraonline.org ).

**Comment by mdoering** [comment]
All data we generate comes from api.checklistbank.org - that would be a logical place for the ids. Or even a new id.checklistbank.org domain which would be safer against future changes.

**Comment by mdoering** [comment]
just deployed to pro

**Comment by rdmpage** [comment]
Looks good - many thanks for doing this so quickly!
