### ISSUE TITLE
Dead links to the documentation

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#190]
For attention of @mdoering or @olafbanki: 
Working with Paris on restoring pipelines for DBTNT checklists, I found that two links to the documentations are dead:

>A dictionary of nomenclatural statuses: http://api.col.plus/vocab/nomstatus (dead link? – reported to Markus)
Name relationships: http://api.col.plus/vocab/nomreltype (dead link? – reported to Markus)

**Comment by yroskov** [comment]
Do we have links to CoLDP documents in the portal? I didn't find right page which I can point to developers.

**Comment by mdoering** [comment]
Simply replace col.plus with the current domain checklistbank.org:

https://api.checklistbank.org/vocab/nomstatus
https://api.checklistbank.org/vocab/nomreltype

Where did you find those old links?
