### ISSUE TITLE
CoL: GSD logos disappeared

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#206]
_for attention of @thomasstjerne & @mdoering_ 

**Describe the bug**
There are **no GSD logos on GSD pages, Species pages and on Source Datasets page** 
Logo is an important attribute of credits in the CoL. I cannot say, when exactly this bug was introduced, but logos are missing in October edition.

https://www.catalogueoflife.org/data/dataset/2144
![image](https://github.com/CatalogueOfLife/portal/assets/28574252/e8ba1381-172e-41c6-8806-92b45fd4a614)

https://www.catalogueoflife.org/data/taxon/85f72796-e404-49c0-ba36-710d08213464
![image](https://github.com/CatalogueOfLife/portal/assets/28574252/632e0d4e-7626-462d-9fde-efc507c77f6c)

https://www.catalogueoflife.org/data/source-datasets
![image](https://github.com/CatalogueOfLife/portal/assets/28574252/23a210d4-5f49-4665-8d35-30a755aac8b0)

Expected behavior:
Logos are present in AC23 @ CLB

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/ef3ecf09-0367-4b10-8bb4-42873b1acc3c)

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/bb5078b0-0057-423b-a017-1c5a77339e71)

**Browser:**
FireFox 119.0

**Comment by mdoering** [comment]
The logo is fetched from here which is correct: https://api.checklistbank.org/image/272972/source/2144/logo?size=MEDIUM
There just isnt anything. Why I need to see...

**Comment by yroskov** [comment]
Hmm... Logos are present in the CLB, they did not pass in the final product. Who should fix this bug?

https://www.checklistbank.org/dataset/2144/about

**Comment by mdoering** [comment]
@thomasstjerne the UI uses a pretty wrong API URL.
It should be https://api.checklistbank.org/dataset/272972/logo/source/2144?size=MEDIUM
