### ISSUE TITLE
CoL PREVIEW: there is no free access to GSD page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#207]
**Describe the bug**
Strangely, login and password are requested when I clicked link to the Source Dataset link on Species page at https://preview.catalogueoflife.org/data/taxon/3YWKQ.

As a result, I get this at https://preview.catalogueoflife.org/data/taxon/3YWKQ
![image](https://github.com/CatalogueOfLife/portal/assets/28574252/1909076d-648f-4e1c-891f-5f8e17fe9902)

**Comment by mdoering** [comment]
@thomasstjerne wasnt that always like that because of private images? Vaguely remember

**Comment by mdoering** [comment]
It is for the logo image only - it always was like that and there is no way around it if I understand.
Once you log in it is saved for future requests. And if you don't have a login that works you can still see the page - just not the logo

**Comment by mdoering** [comment]
Where exactly are the logos missing? The prod and preview sites works fine for me if that is the place you refer to: https://www.catalogueoflife.org/data/dataset/1166
https://preview.catalogueoflife.org/data/dataset/1166

**Comment by yroskov** [comment]
Yes, you are right, https://github.com/CatalogueOfLife/portal/issues/206 is fixed now. 

PaleoBioDB logo is missing, but that is a problem on our side (it is vanished in CLB)
