### ISSUE TITLE
Portal (production): Incorrect GSD version on the GSD page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#213]
It occurs, that the production Portal displays GSD **Version** and **Isued** date incorrectly on **GSD page**, showing date of CoL release for all, instead of individual GSD versions & data.

Probably, it's the same issue as https://github.com/CatalogueOfLife/backend/issues/1333

For example:
https://www.catalogueoflife.org/data/dataset/2207
https://www.catalogueoflife.org/data/dataset/2317
https://www.catalogueoflife.org/data/dataset/1502

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/225420ff-f164-4d40-835c-1b923b6c44b5)

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/19b80740-cd03-4b08-a03b-fd3eab61f303)

![image](https://github.com/CatalogueOfLife/portal/assets/28574252/a42346e5-bcea-4658-a1bd-b51730109cf9)

**Comment by yroskov** [comment]
For attention of @mdoering & @thomasstjerne

**Comment by mdoering** [comment]
same as https://github.com/CatalogueOfLife/backend/issues/1333
