### ISSUE TITLE
Taxonomic Coverage line is missing now in a set of GSDs

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#214]
Taxonomic Coverage (taxon & classification string) is missing now in a set of GSD metadata. N/A value appears instead.
_for example:_
![image](https://github.com/CatalogueOfLife/testing/assets/28574252/159975c7-37c0-4b0d-b1a1-7c8f9e563410)
https://preview.catalogueoflife.org/data/dataset/1204
https://preview.catalogueoflife.org/data/dataset/1101
https://preview.catalogueoflife.org/data/dataset/1061
https://preview.catalogueoflife.org/data/dataset/1169
https://preview.catalogueoflife.org/data/dataset/1089
https://preview.catalogueoflife.org/data/dataset/1065
etc.

@mdoering, if I am not wrong, Taxonomic Coverage line is generated by the software.

**Comment by mdoering** [comment]
@thomasstjerne I can see failing search requests like the following in the page resources:

> https://api.checklistbank.org/dataset/298863/nameusage/search?TAXON_ID=C2L&rank=undefined&q=Staphylinoidea

Looks like the UI always expects a rank to exist. That should be optional. Instead we should add a `status=accepted` parameter to avoid yielding synonyms with the same name:

 - https://api.checklistbank.org/dataset/298863/nameusage/search?TAXON_ID=C2L&q=Staphylinoidea
 - https://api.checklistbank.org/dataset/298863/nameusage/search?TAXON_ID=C2L&status=accepted&q=Staphylinoidea
 
Said that I do not understand why no rank is given for the sector subject. That really should not be
