### ISSUE TITLE
Count source data not correct

### ISSUE THREAD

**Issue by olafbanki** [CatalogueOfLife/portal#216]
**Count source data not correct**
https://www.catalogueoflife.org/data/source-datasets It shows that there are 173 data sources; this is not correct the number is 164

**Comment by yroskov** [comment]
I spotted the same problem, contacting potential new GSD authors. Incorrect number of contributing checklists is very confusing. Could it be fixed, please?

**Comment by olafbanki** [comment]
Yes, I spotted and notified Markus of this same problem. It states that there are 172 data sources, but there are 164.

**Comment by olafbanki** [comment]
@thomasstjerne could you look into what is causing this?

**Comment by mdoering** [comment]
see above, empty publishers are counted but need to be excluded if empty

**Comment by thomasstjerne** [comment]
I could do a frontend filtering if needed.
But would it maybe make more sense if https://api.checklistbank.org/dataset/301819/sector/publisher was filtered so publishers with zero sectors didn´t show up?
If we choose to filter on the frontend, should it filter on `sectorCount
:
0` or `usagesCount
:
0` in this endpoint:
https://api.checklistbank.org/dataset/301819/sector/publisher/0674aea0-a7e1-11d8-9534-b8a03c50a862/metrics

**Comment by mdoering** [comment]
the API needs to list all publishers regardless of number of sectors - otherwise you cannot show & manage them. I would filter on sector counts
