### ISSUE TITLE
Credits to GSDs are disappeared in the Tree in production & preview portals

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#220]
**Describe the bug**
Credits to GSDs in the Tree are disappeared in both preview and production websites:

Preview at https://preview.catalogueoflife.org/?taxonKey=8NKFG
![image](https://github.com/user-attachments/assets/569e253d-b399-4935-889c-b04aa1ad0593)

and Production at https://www.catalogueoflife.org/?taxonKey=8NKFG (only species counts shown)
![image](https://github.com/user-attachments/assets/9e9d2b8e-e267-4d41-9484-e0b1837b7612)

**To Reproduce**
1. Go to https://www.catalogueoflife.org/
2. Tick check-box Info
4. See error = no credits to GSDs supplied data in the taxon node

**Screenshots**
See above

**Browser:**
Firefox

**Comment by mdoering** [comment]
@thomasstjerne the tree API calls have no `type` parameter any longer - as we discussed would be best as the default for users of the component. But in the portal we need `type=PROJECT` to get the source dataset keys: https://api.checklistbank.org/dataset/305232/tree/CCQKT/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=305232&type=PROJECT

Do we need to change the usage of the component on the portal?

**Comment by mdoering** [comment]
https://github.com/CatalogueOfLife/portal/commit/99e364fa70510ada708030b674953a71ad2cb1b0
