### ISSUE TITLE
Show species counts in tree

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#23]
The old UI shows the [number of species](http://www.catalogueoflife.org/annual-checklist/2019/browse/tree?c629be19c77802da850cf8d2775b6a06) included for every (higher) taxon in the tree:

<img width="1036" alt="Screenshot 2020-09-03 at 13 55 38" src="https://user-images.githubusercontent.com/327505/92112240-c8326780-eded-11ea-84fb-aca02c157853.png">

It also shows the number of extinct and estimated species.
The new portal only provides the estimates which are offered by the Tree API:

<img width="767" alt="Screenshot 2020-09-03 at 14 00 45" src="https://user-images.githubusercontent.com/327505/92112324-e5ffcc80-eded-11ea-9d7d-de9eebd8478d.png">

Should we include species counts for both living and extinct in the Tree API?
Or would some other (additional?) counts be more informative, e.g. by accepted taxa for each major ranks?
Similar to what we now have in the taxon details view?
https://data.catalogue.life/dataset/3/taxon/bfb709db-491c-48b6-80f5-32ef14f63e4f

<img width="866" alt="Screenshot 2020-09-03 at 14 05 15" src="https://user-images.githubusercontent.com/327505/92112711-8524c400-edee-11ea-90f8-304e41f31f19.png">

**Comment by dhobern** [comment]
I would probably not try to include counts for the intermediate ranks. The count of 31 subfamilies and two tribes for Tracheophyta is pretty meaningless since there are 510 families - the fact that some of these families have been subdivided but most haven't is confusing.

I guess the main value of the counts is to indicate the scale of the underlying data, so some kind of accepted species count seems adequate.

**Comment by mdoering** [comment]
Now that we have a varnish cache in front of the API for releases we could also consider to take the counts from ElasticSearch for each node and decorate the tree clientside, @thomasstjernel. This is of course never great as it can result in lots of calls, but it might be sth we can do quickly as a start and replace later on if its a drag. Caching results at least should protect us from seriously slow pages.

E.g. for Animalia:
https://api.catalogue.life/dataset/3LR/tree/061950e4-9782-4d1a-9c87-dcf375788e6b/children

The ES count would be:
https://api.catalogue.life/dataset/3LR/nameusage/search?taxonID=061950e4-9782-4d1a-9c87-dcf375788e6b&rank=species&limit=0

... going down from 200ms to 50ms here.

**Comment by thomasstjerne** [comment]
> @thomasstjerne Now that we have a varnish cache in front of the API for releases we could also consider to take the counts from ElasticSearch for each node and decorate the tree clientside. This is of course never great as it can result in lots of calls, but it might be sth we can do quickly as a start and replace later on if its a drag. Caching results at least should protect us from seriously slow pages.

I am not keen on introducing temporary solutions in the UI for this. Wouldn´t it be possible to decorate the tree response with data from elastic on the fly in the backend?  I mean, like the frontend could do if it had its own backend (like the GBIF portal).

Then it would be transparent for the frontend and the data could be replaced by sth generated at release time. And it would save a large number of requests from the UI, which would be advantageous for users not located close to GBIF servers.

**Comment by mdoering** [comment]
I was thinking about that too. Doable sure, but it would make the response a lot slower. Decorating it clientside would show the tree and then fetch counts and could render them as they come in. That way more responsive. If its via the backend I am in favor of preprocessing it for releases and external datasets

**Comment by mdoering** [comment]
I have added optional taxon counts to the tree API that are added to the response when a `countBy=SPECIES` query parameter is present. Instead of SPECIES any rank can be given. It is not very performant to do ES queries for every node in the response, so please do not yet use this on the public portal pages. We will need a precalculated version for that, not on the fly queries to ES.

**Comment by mdoering** [comment]
I have implemented taxon metrics for releases and will add the species counts to the tree API
