### ISSUE TITLE
Show list of historic releases

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#25]
There should be a release history page that lists previous releases.
Each release should have a link to the dockerized annual edition and if existing one or more links to downloads for the entire data.

DwC-A downloads for older annual releases do exist since 2012 and should be linked:
http://api.catalogue.life/download/col/annual/

Old page:
https://www.catalogueoflife.org/content/previous-versions-annual-checklist

**Comment by dhobern** [comment]
A page for this would be fine - it could even initially just be a blog post

**Comment by mdoering** [comment]
The page should then list both the dwc archive and the link to the dynamic docker UI for each year.

**Comment by mdoering** [comment]
mysql dumps uploaded to the same folder as the dwcas:
http://api.catalogue.life/download/col/annual/
