### ISSUE TITLE
List of Contributing Datasets

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#26]
https://www.dev.catalogue.life/data/contributing-datasets.html

![image](https://user-images.githubusercontent.com/28574252/93223806-0e64c080-f736-11ea-8058-a2e914253a03.png)

Essential change needed:

- [ ] **Title**. Please use Alias + Full GSD Name (for example, SF Coreoidea: Coreoidea Species File), or Alias only (SF Coreoidea).

Proposed improvements:

- [ ] Add column **Kingdom**. It helps users better understand a taxonomic location of the GSD.

- [ ] Add option to expand statistics for Genera, Families, Orders, Classes, Phyla, Kingdoms covered by GSD.

**Comment by mdoering** [comment]
- alias/title: I would be in favour of just using the alias, definitely not both
 - Showing the kingdom is a good idea, but we don't have that information readily at hand. 
We could generate this during the release process based on the sectors if we want it, but that warrants an API change first.
 - expand statistics: 👍 which exactly needs to be decided. Proposal: Table of accepted name counts by rank, with counts always being both living/extinct (synonyms), e.g. `genus: 13756 / 788† / 2345 synonyms`. Plus at the end total counts of  vernacular names, distributions and references
