### ISSUE TITLE
Reduce heading size

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#30]
The subheaders on pages feel very large and disruptive.
I would be in favor of reducing their size considerably.

Currenty:
<img width="1397" alt="Screenshot 2020-09-17 at 13 03 01" src="https://user-images.githubusercontent.com/327505/93462156-28450580-f8e6-11ea-9de7-bc7d466259da.png">

Removed the H2 font-size: 2.1428571429rem from type.scss:

<img width="1397" alt="Screenshot 2020-09-17 at 13 02 45" src="https://user-images.githubusercontent.com/327505/93462178-32670400-f8e6-11ea-82a3-e85f56885ff3.png">

**Comment by dhobern** [comment]
Fixed
