### ISSUE TITLE
404 errors in search results

### ISSUE THREAD

**Issue by dremsen** [CatalogueOfLife/portal#33]
I've come across several 404 errors when following links to taxon information from search results in dev.catalogue.life

Example
Search for "vulgaris" in field _input search text_.   The majority of synonym results return 404 errors when the name is clicked to link to record details.  Accepted name records appear to work properly.
<img width="1204" alt="Screen Shot 2020-09-23 at 10 38 04 AM" src="https://user-images.githubusercontent.com/62540/94027521-ece48400-fd88-11ea-83a8-96b0ac9abbc1.png">

Example 
Search for "pomatomus" in field _input search text_.  The list of results includes the name Pomatomus skib as a synonym of Pomatomus saltatrix.  Clicking Pomatomus skib results in a 404 error that includes "Taxon 2206:10a264bc-e783-4b40-af4d-21b171b6c88e does not exist"

**Comment by mdoering** [comment]
@thomasstjerne indeed the UI uses the synonyms usageID as a parameter for the taxon API.
It should use the [usage.accepted.id](url) instead
See https://api.catalogue.life/dataset/3LR/nameusage/1d967259-06b5-406a-adae-b0b251496179
