### ISSUE TITLE
Remove Nomenclatural status search filter

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#37]
We dont have any data on this in the COL right now, remove it from the COL portal search

**Comment by thomasstjerne** [comment]
I think there are data - its just the facet that is oddly named https://github.com/CatalogueOfLife/backend/issues/853 
`{
"value": "unacceptable",
"count": 12071
},
{
"value": "not established",
"count": 3223
},
{
"value": "rejected",
"count": 288
},
{
"value": "doubtful",
"count": 109
},
{
"value": "conserved",
"count": 16
},
{
"value": "manuscript",
"count": 4
}`

**Comment by thomasstjerne** [comment]
@mdoering should we still remove this as we have now solved the facet naming? 
I think its useful to keep it

**Comment by mdoering** [comment]
You're right. As long as its in the advanced section lets keep it!
