### ISSUE TITLE
Add link to subscribe to user mailing list

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#39]
https://lists.gbif.org/mailman/listinfo/col-users

**Comment by dhobern** [comment]
I fixed this one eight days ago -
https://github.com/CatalogueOfLife/portal/blob/master/articles/help/contact.md

Changes used to propagate automatically to the dev site. I assume someone
has to trigger a propagate to the site under the new URL.

The changes also included using some of Jan Huijbers' photos in place of
some of mine.

Donald

-- 

*Donald Hobern* / dhobern@gmail.com / +61 420511471
Araba Bioscan Project <https://stangeia.hobern.net/araba-bioscan-project/>
/ Pterophoroidea Catalogue <https://pterophoroidea.hobern.net/> / Alucitoidea
Catalogue <https://alucitoidea.hobern.net/>
ORCID: 0000-0001-6492-4016 <https://orcid.org/0000-0001-6492-4016> / Blog
<https://stangeia.hobern.net/> / iNaturalist
<https://inaturalist.ala.org.au/people/dhobern> / Flickr
<https://www.flickr.com/photos/dhobern/>/ GitHub
<https://github.com/dhobern> / Twitter <https://twitter.com/dhobern>

**Comment by mdoering** [comment]
The dev site does still build with every push to github.
Your change was Build #159 www.dev.catalogueoflife.org (10-Nov-2020 12:04:57):
https://builds.gbif.org/job/col-portal/159/

Something missing from there?

**Comment by dhobern** [comment]
Thanks - what is the processing for then pushing to the deployed version?

**Comment by mdoering** [comment]
manually trigger the jenkins build job. I'll do that now.
In the future please ping me or @thomasstjerne .
