### ISSUE TITLE
Missing What’s new page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#41]
CoL as a product needs chapters:

**What’s new?** (new entries, updates and data improvements; plus history through all months in a year cycle): http://www.catalogueoflife.org/col/info/special 

**How to cite this work** (a list of recommended citations for GSDs in CoL): http://www.catalogueoflife.org/annual-checklist/2019/info/cite. 
This list should be automatically generated using GSD and CoL metadata.

**Acknowledgements**. http://www.catalogueoflife.org/col/info/acknowledgements

**Comment by yroskov** [comment]
Proposal for improvement:

A monthly batch of **What's new?** should be also included in metadata of each CoL release.

**Comment by mdoering** [comment]
Not sure how to treat this best.
I agree a "whats new paragraph" should be added to the metadata of a release in the API so we can show it not only in the portal but also ChecklistBank. Created new issue https://github.com/CatalogueOfLife/backend/issues/867

**Comment by chantalhuijbers** [comment]
This is work in progress, but no stoppers for Go Live.
Page with How to Cite is included and also linked to above the tree: https://www.catalogue.life/content/colusage.html#recommended-citations

**Comment by chantalhuijbers** [comment]
What's New will be included as a field in the project metadata.
We will create a dynamic dataset page for the current checklist linked to from the front page.

**Comment by mdoering** [comment]
Thinking about it again I wonder if we can do an even simpler solution now.

How about just appending a new paragraph to the descriptions which is the whats new section? The description holds several paragraphs anyways. It's just part of the description. Many datasets have such whats new paragraphs in the description already.

Just keep the whats new text separate at the bottom with an empty line

**Comment by yroskov** [comment]
>appending a new paragraph to the descriptions which is the whats new section? - I agree.
At this moment, I am doing this, but in an ugly look. For example, in September edition:
![image](https://user-images.githubusercontent.com/28574252/100764986-9add6180-33bc-11eb-9389-07e69670d977.png)

**Comment by mdoering** [comment]
just leave an empty line so you simpler to see the whats new section.
We should make sure to render that more nicely soon

<img width="1055" alt="Screenshot 2020-12-01 at 17 21 47" src="https://user-images.githubusercontent.com/327505/100767262-d6e2e780-33f9-11eb-83f0-cdd5da0ebcc1.png">

**Comment by mdoering** [comment]
https://www.dev.catalogueoflife.org/data/metadata

@chantalhuijbers @dhobern feel free to modify this basic version as you think.
I would suggest to also add it to the data menu.

**Comment by mdoering** [comment]
Moving the Acknowledgements page to a dedicated issue https://github.com/CatalogueOfLife/portal/issues/127

The existing [whats new pages](http://www.catalogueoflife.org/annual-checklist/2019/info/special) has been 3 things:

1.  List of new datasets
2.  List of updated datasets
1.  Free text description of other changes


When we make use of the [source metrics page](https://data.catalogueoflife.org/catalogue/3/sourcemetrics?releaseKey=2242), comparing to the previous release we get all the added and changed datasets with many more metrics if wanted. A user can also compare not just to the last release but to any release.

This leaves only the free text changes which we could store either as part of the description or as a dedicated changelog text. 
It is probably best to keep this in a dedicated property. Then we can also aggregate all changes across several versions and maybe even show them all also in the source metrics page?

**Comment by yroskov** [comment]
As the editor, I need items
-     List of new datasets
-     List of updated datasets
-     Free text description of other changes
**maintained manually**. It's a brief message from the editor to CoL users.

However, it would be nice, if **all** changes in the dataset will be exposed to the user in addition to brief editor's message. I would prefer to see this as an additional service via API (automatic notification about all changed records by GSDs, by fields, etc.).

**Comment by mdoering** [comment]
We could also consider to only keep a short changelog in the dataset metadata (as a new field), and then link out to some changelog page which is maintained in the portal as a single markdown page. We do sth similar in GBIF now where we have a short release notes section for the GBIF backbone:
https://www.gbif.org/release-notes

... which then links to a more detailed description:
https://github.com/gbif/checklistbank/blob/master/docs/backbone-builds/2021-03-03.md



If we keep the short overview of changes in the datasets metadata it is archived and we can get a list of all changes between any version easily then. I think this is valuable.

**Comment by yroskov** [comment]
Good idea: to keep a short message with a link to detailed reports on changes.

@gdower & I has proposed a prototype for a log of new and updated GSDs (a table GSD vs CoL release with values "new", "updated"). It is an addition to a short editor's message.
