### ISSUE TITLE
Link to checklist bank

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#52]
on taxon pages it would be good to have a link to the same page in CLB to get more insight into the record

**Comment by mdoering** [comment]
@thomasstjerne can we just add a link "View in Checklist Bank" below the "Link to original resource" in the details page?
The page https://www.catalogueoflife.org/data/taxon/FVY would be linking to https://data.catalogueoflife.org/dataset/3LR/taxon/FVY with 3LR probably being replaced by the actual datasetKey configured.

**Comment by mdoering** [comment]
In the future we could also link out to GBIF and other places that make use of the COL identifiers

**Comment by chantalhuijbers** [comment]
I still don't really understand the added value of a link to CLB for view only users. Doesn't it show exactly the same information as in the COL portal? What requirement do we fulfill with this link?

**Comment by mdoering** [comment]
The taxon page does indeed show nearly the exact same information. But we do also link to a names page and there should be obvious ways to crosswalk to the source record (e.g. ITIS) and any other dataset with the same name. It gives you an entry point into CLB. But maybe that is just me who often wants to find the same page in CLB or GBIF. 

For future annual releases we also need to link to CLB somehow.

**Comment by mdoering** [comment]
done
