### ISSUE TITLE
Allow tree browser to have unlimited height

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#53]
Tree scrolling is restricted to a small window within the page. This results in two scroll bars which is bad.
You cannot view the entire tree.

Allow to see the entire opened tree on the page

**Comment by gdower** [comment]
Maybe when a user first interacts with the tree on the front page, it should redirect you to the expanded browse page, although even on that page the interface is too small compared to the header image:

http://www.catalogue.life/data/browse.html

![Screenshot_20201104_160212](https://user-images.githubusercontent.com/8573609/98172742-80948e80-1eb7-11eb-93a7-3fbe72d0deb9.png)

**Comment by thomasstjerne** [comment]
Scrolling to a specific taxon ( using the search box above the tree) only works if the height is fixed. 
The react components doesn´t control the entire page so the searched taxon will end up in the bottom of the page, in most case far out of the bottom of the page.

Maybe the tree could somehow keep track of the number of children of the most recently opened node, and then update the fixed height dynamically. It might work, but there is no easy fix if we want to preserve the "scroll to taxon" functionality

**Comment by mdoering** [comment]
I'd rather have a large page without a second scrollbar and miss the scroll to taxon functionality.
Especially if we could get close by tracking the tree size

**Comment by thomasstjerne** [comment]
This is on a separate branch now and released as a beta and deployed to http://www.dev.catalogueoflife.org/.
Managed to do a hand-rolled scroll to taxon that works on the full tree. 
But removing the virtual scroll makes the tree feel somewhat slower and I had to bring back paging of children when there are many.

**Comment by mdoering** [comment]
Feels ok here, but in general I hate to revert in performance. Silly idea, could we simply scroll down to the bottom of the page maybe (or better some fixed distance from the bottom)? The searched and opened taxon nearly always is going to be close to the bottom unless someone had opened the tree manually before.
