### ISSUE TITLE
Retrieve logos from release

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#54]
currently the tree browser looks for logos from the live version of the dataset:
https://api.catalogue.life/dataset/1024/logo?size=SMALL

We should use the archived version instead:
 - it might differ
 - the live one might even be deleted by now
 - only release URLs starting with /dataset/{RELEASEKEY} are cached

Instead we should use `/dataset/{key}/source/{id}/logo`

**Comment by mdoering** [comment]
@thomasstjerne is that quick to change? It would reduce the public portal requests considerably similar to the removal of sector calls.

**Comment by thomasstjerne** [comment]
It seems the logos currently is not in the latest realease https://api.catalogue.life/dataset/3LR/source/1014/logo

**Comment by mdoering** [comment]
looks like the service mixes up release and source key

**Comment by mdoering** [comment]
works now!
