### ISSUE TITLE
Front page search box

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#6]
Add a simple search box on the front page with a name suggest that takes you to a taxon page or the fuzzy search in case no suggested name was used.

**Comment by dhobern** [comment]
This is important I think the front page should have very little other than a search box

**Comment by mdoering** [comment]
Alternatively or in addition we could already show the tree to be browsed.
There was also a debate on tuesday when we looked at the current front page to show some basic metrics.
And probably the latest release version/date somewhere?

**Comment by dhobern** [comment]
Fixed
