### ISSUE TITLE
Broken links in Downloads text

### ISSUE THREAD

**Issue by olafbanki** [CatalogueOfLife/portal#62]
<img width="1218" alt="Screenshot 2020-11-08 at 21 41 20" src="https://user-images.githubusercontent.com/28391627/98484754-ebc0c680-2211-11eb-9c16-b08a2e2c2d42.png">

Links for 'previous versions' and 'downloaded from here' do not resolve.

**Comment by dhobern** [comment]
Fixed the first part. Cannot find a current link for the second part. I have commented it out for now. Do we still have a URL to access the old SQL dumps, etc.?

**Comment by olafbanki** [comment]
Indeed this lik http://api.catalogue.life/download/col/annual/ is no longer resolving @mdoering could you point out the right URL?

**Comment by mdoering** [comment]
What is the page with the broken links?
Downloads have their own subdomain now and do not go through the API anymore:
https://download.catalogue.life/

I had changed the [previous versions page](https://www.catalogue.life/data/archives.html) accordingly, linking also all sql dumps directly.
Where else is the link used?

**Comment by mdoering** [comment]
I would suggest to remove the second part "Darwin Core Archives of historic annual COL Checklists (2012-2019) and/or MySQL dumps (2005-2019) can also be downloaded from here." entirely and keep all links from the previous page only

**Comment by dhobern** [comment]
For the time being, I've fixed it to point to the download subdomain.
