### ISSUE TITLE
(Re)consider prominence of species estimates and completeness metrics

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/portal#66]
The new site looks good! I have a couple of observations that I wonder should be (re)considered.

The homepage prominently shows "est spp." for taxa which I assume means estimated species counts. I don't know where the numbers come from, but they look rather low compared to what I'd anticipate seeing here - e.g. 1M insects, 140k fungi. Given the difficulties in projecting realistic counts, I wonder if COL would be better of simply leaving these off altogether to avoid potentially turning newcomers off at the home page?

Slightly related are the completeness and confidence scores on the [dataset pages](https://www.catalogue.life/data/dataset/2144) which also appear on individual [taxon pages](https://www.catalogue.life/data/taxon/5GYWL). It is not explained what these are, and seem to be internal matters that probably shouldn't be exposed to a user - or at least they should be very clearly explained.

**Comment by dhobern** [comment]
Thanks, Tim. I agree about the current confidence measures and will be discussing tonight how we may shift to some more formal criteria. The current scale is self-asserted and pretty meaningles. As for counts, I'll give it some more thought.

**Comment by mdoering** [comment]
The original plan based on the [old portal](http://www.catalogueoflife.org/annual-checklist/2019/browse/tree?57a5185fb424799c7da3fbb3ea8ca858) is to:
 - offer options to hide estimates, extinct taxa and actual species counts (not impleneted yet)
 - cite the source of the estimate (usually its been published, not just guessed) - its visible in CLB & API

As for estimate `types` please see also https://github.com/CatalogueOfLife/backend/issues/828

The old UI did explain what ratings are:
http://www.catalogueoflife.org/annual-checklist/2019/info/databases

... and how estimates and the extinct flag works:
http://www.catalogueoflife.org/annual-checklist/2019/info/hierarchy

We also need some explanation of all this and probably more, e.g. on the taxonomic status (provisional, misapplied) or how species distributions work.

**Comment by mdoering** [comment]
I agree we should turn estimates off by default and allow users to see it if requested

**Comment by mdoering** [comment]
we hide estimates entirely for now
