### ISSUE TITLE
Create Acknowledgements page

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#67]
As discussed with Global Team in November we want a full Acknowledgements page that lists not only the sources but each and every person that contributed to the COL or its sources.

Create a dynamic page driven by the API which needs to extract authors & editors from metadata and distinct scrutinizers from all taxa in COL.

**Comment by mdoering** [comment]
API: https://github.com/CatalogueOfLife/backend/issues/915

**Comment by mdoering** [comment]
See also https://github.com/CatalogueOfLife/portal/issues/41

**Comment by chantalhuijbers** [comment]
See also https://github.com/CatalogueOfLife/portal/issues/127
