### ISSUE TITLE
Tree down in portal: NETWORK ERROR - HTTP method: GET

### ISSUE THREAD

**Issue by olafbanki** [CatalogueOfLife/portal#68]
See https://www.catalogue.life/

Same for contributing datasets: https://www.catalogue.life/data/contributing-datasets.html

Same for top page of COL ChecklistBank: https://data.catalogue.life/
<img width="1280" alt="Screenshot 2020-11-21 at 15 54 10" src="https://user-images.githubusercontent.com/28391627/99880163-06337080-2c12-11eb-9e4d-d93a81a50769.png">
<img width="1280" alt="Screenshot 2020-11-21 at 12 08 35" src="https://user-images.githubusercontent.com/28391627/99880171-121f3280-2c12-11eb-8ca1-725eca8988e3.png">

**Comment by thomasstjerne** [comment]
Missing CORS header:

Access to XMLHttpRequest at 'https://api.catalogue.life/dataset/3LR/source' from origin 'https://www.catalogue.life' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mdoering** [comment]
Damn, the old problem back again: https://github.com/CatalogueOfLife/deploy/issues/3

**Comment by mdoering** [comment]
I've restarted varnish and it works again.
This is a serious caching issue we need to solve, but I'll close it here and keep the deploy issue open for me and Matt to look at next week

**Comment by olafbanki** [comment]
Ok sounds good. I thought Tim R. was prepared to look into this Varnish issue.
