### ISSUE TITLE
Tree options

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#69]
Based on unresolved issues in #27 there still needs to be a way to toggle logos, stats and an extinct filter in the tree component.

 - [ ] Missing estimation source citation. There should be an info icon that shows the estimate source but also the stats (estiamtes + species counts tbd) again and a list of all sources by name. 
 - [x] toggle to turn on/off extra infos. I would not use 3 different toggles like we have in the old UI, but instead show all (estimates, future species counts, logo) or nothing with the above info icon always being present to get the information on demand. 
 - [x] extinct toggle to setting the [extinct flag in the tree API](https://github.com/CatalogueOfLife/backend/issues/837) to only browse living taxa.

**Comment by thomasstjerne** [comment]
This was deployed to dev last week

**Comment by mdoering** [comment]
Ha, great! I must have used a cached version.

Is it necessary to have "Show" in the label? I would prefer a short toggle with just "Infos" and "Extinct" and consider to exclude Infos by default

**Comment by mdoering** [comment]
Opening as the estimation source reference is not shown
