### ISSUE TITLE
Blank lines on GSD metadata page in Firefox

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/portal#72]
...empty blinking lines between sections English name of the Group and Abstract on GSD metadatad page in **Firefox 83.0 (64-bit, Windows)** 
as reported in https://github.com/CatalogueOfLife/testing/issues/1
@thomasstjerne 

![image](https://user-images.githubusercontent.com/28574252/100112630-111a1b00-2e35-11eb-99d3-d74e47d0f047.png)

**Comment by thomasstjerne** [comment]
duplicate of https://github.com/CatalogueOfLife/portal/issues/72

**Comment by mdoering** [comment]
duplicate of #73 maybe?

**Comment by thomasstjerne** [comment]
Its the preflight of https://api.catalogue.life/vocab/rank that fails

**Comment by mdoering** [comment]
and why does it fail? It's not even authenticated

**Comment by yroskov** [comment]
Firefox for Win 83.0 (64-bit).
Counts are visible now in my browser (fixed):

![image](https://user-images.githubusercontent.com/28574252/100237639-cf50a980-2ef4-11eb-8793-f43f9796d6bd.png)

However, Taxonomic coverage is not visible in my Firefox (it's visible in Chrome). I opened a new ticket: https://github.com/CatalogueOfLife/backend/issues/923

**Comment by mdoering** [comment]
maybe some cross browser tests would be nice: https://www.softwaretestinghelp.com/best-cross-browser-testing-tools-to-ease-your-browser-compatibility-testing-efforts/
