### ISSUE TITLE
Preview requests API authentication

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#73]
probably logo images still

**Comment by thomasstjerne** [comment]
Please remove auth for images. Or should I simply hide them in preview env?

**Comment by mdoering** [comment]
removing auth is not simple as everything under dataset/XYZ is hidden without knowing what is actually requested

**Comment by mdoering** [comment]
could we not just load the image via JS just as we do with other API calls?

**Comment by mdoering** [comment]
Could even be a small React component for dataset logos loaded through the API

**Comment by mdoering** [comment]
If this is far too difficult I can probably exclude the logos from requiring authentication - a bit of a hack though

**Comment by thomasstjerne** [comment]
I did the authenticated urls now - but I think Chrome will block this. Works in Firefox though
