### ISSUE TITLE
Add ColDP and DwC-A download link

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#76]
The current version of COL will be available as a DwC-A and ColDP archive soon here:
https://download.catalogue.life/col/

There will be a symlink that always points to the latest version of the archives.
This URL should be added to the portal for users to download.

There also needs to be some help page that explains both formats for the end user.

**Comment by chantalhuijbers** [comment]
Added to the Prevoius Versions page: https://www.catalogue.life/data/archives.html
