### ISSUE TITLE
Prepare go live blog post!

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#80]
Write a blog post that 
 - introduces the new COL portal
 - explains that the old Naturalis services are out of service
 - that we have a new set of identifiers, linking also to the species ID mapping file for people that wish to update to the new set of stable COL IDs
 - that we retain the old API and Website URLs for some time for smooth transition
 - that work continues & we welcome feedback (how to)

**Comment by mdoering** [comment]
id maps is here:
https://download.catalogue.life/col/legacy_id_map.tsv.gz

with 3 columns: oldID, newID, name
```
0000008976cbd2650e0c0be83c9959d7	3WUWE	Lysipomia aretioides Kunth
000002a1a78dc28bb9008feee20040e2	4ZWHR	Stenocercus apurimacus Fritts, 1972
0000031379c1047128150d59c80e86fb	4WGF4	Semidalis bicornis Z.-q. Liu & C.-k. Yang, 1993
00000529f9fa3f3b940aebd7dc3c8862	33L8K	Cyrtidula quercus (A. Massal.) Minks
000009bdaa52dc6263e5f09087a9df4a	3N8XQ	Hydroporus stagnalis Gemminger & Harold, 1868
000012d8d37178a9f860e3ef16a59717	4Z67C	Spio nemertinaeformis Czerniavsky, 1881
0000158c68e60e8d9bf09313321911e9	ZS72	Crustulina starmuehlneri Kritscher, 1966
00001707783060efbeadaa5fc33b8519	3HJH8	Guarea thompsonii Sprague & Hutch.
00001ec7cad71d7c05c2f6870430b9b9	SNUC	Ceratophygadeuon impressus Townes, 1983
```

**Comment by mdoering** [comment]
legacy data URLs redirected:
 - species: http://www.catalogue.life/col/details/species/id/c526234e655cec65618f58161d24932a
 - search: http://www.catalogue.life/col/search/all/key/Dracula+bella/fossil/1
 - databases: http://www.catalogue.life/col/details/database/id/8

**Comment by chantalhuijbers** [comment]
I have started a draft here: https://docs.google.com/document/d/1qBR0lgWvdqoKtEpU6Tg3hD43g6U9yozq8in3E0mCuOk/edit?usp=sharing
