### ISSUE TITLE
SEO for taxon pages

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#88]
We want google to index COL taxon pages.
How can this best be supported? The portal contains a jekyll build sitemap that excludes all dynamic pages.

**Comment by thomasstjerne** [comment]
In MySQL you would run sth like:
`SELECT CONCAT('https://www.catalogueoflife.org/taxon/', id) INTO OUTFILE 'sitemap.txt' FROM Taxon`;

I.e., produce a txt file all taxon urls, line by line:
`````
https://www.catalogueoflife.org/taxon/A
https://www.catalogueoflife.org/taxon/P
https://www.catalogueoflife.org/taxon/F
etc etc
``````

**Comment by mdoering** [comment]
we would have to do this on every release and is that enough to help google reading the react page?

**Comment by thomasstjerne** [comment]
Yes, it works fine for dynamic pages.
If we always want every taxon page to be indexed, then it must be done on every release. However, if IDs are stable then the major part of the pages will not be changed from release to release. Maybe it would be sufficient regenerating the sitemap on the yearly release.

**Comment by mdoering** [comment]
does google follow any links on those pages? I read different things.
If so, even new pages could be found and a yearly update would indeed be sufficient

**Comment by mdoering** [comment]
I will produce the sitemap for the current release and we can add it to the portal tomorrow after the release went fine

**Comment by thomasstjerne** [comment]
It can also be uploaded directly to the google developer console. I dont know if there are additional benefits from this approach. It least it would be possible to add an additional sitemap of new taxon ids without redploying

**Comment by mdoering** [comment]
we need to split them into 50.000 per file, i.e. more than 40 maps for over 2 million accepted species.
https://www.sitemaps.org/protocol.html#otherformats

**Comment by mdoering** [comment]
I have added >40 sitemap-[a-z].txt files to the portal and linked them from robots.txt
