### ISSUE TITLE
Make previous CoL archives accessible

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#9]
see http://www.catalogueoflife.org/DCA_Export/archive.php

**Comment by MattBlissett** [comment]
Is that the total storage used, around 6GB?

I will want to go through the intended final setup for the websites, so data is backed up efficiently (there are two ways) and VMs don't have large amounts of static date on local disk.

**Comment by mdoering** [comment]
thats the current total storage for the dwc archives. But we should also offer native mysql dumps for all annual editions. In the new CoL API we also have a download section that we use for exporting datasets: http://api.catalogue.life/download/

It makes sense to place both the historic DwC-A and mysql dumps there too.

**Comment by mdoering** [comment]
I have copied the archives to the API download folder:
http://api.catalogue.life/download/col/

**Comment by mdoering** [comment]
this is not links to previous annual releases on docker, but downloads of the entire AC release data.
Issue is integrated into #25 and can be closed now
