### ISSUE TITLE
Ask for GDPR consent

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#90]
sth jekyll based maybe?
https://jekyllcodex.org/without-plugin/cookie-consent/

**Comment by MattBlissett** [comment]
https://support.google.com/analytics/answer/9976101?hl=en is probably relevant, for a way to gather some statistics when consent is denied.

(Possibly COL could even run in no-consent mode for all users, and perhaps not need to ask at all. I don't know what analytics we'd miss out on, it's not very clear.)
