### ISSUE TITLE
Too many taxon references shown

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#95]
This taxon info only has 6 references:

```
    "referenceIds": [
      "dca34dd0-a6b1-4e98-8a1a-5b7bdd54cf93",
      "aff9b2c2-aec8-4bd9-9b7d-0222a5373bc6",
      "fe5f6ae5-bd2a-4ccc-9a8f-1368ae843f11",
      "c714c1a3-2eeb-4713-8ee9-1cca67e61cde",
      "32ce4f76-e20c-46da-936a-15a71f42343a",
      "875c8b80-dd62-4a8f-b707-48d9d4f95152"
    ]
```

But a lot more are shown:

<img width="826" alt="Screenshot 2020-12-08 at 22 39 46" src="https://user-images.githubusercontent.com/327505/101544647-4f234d00-39a6-11eb-8868-6f211b9800b8.png">

See https://github.com/CatalogueOfLife/backend/issues/929#issuecomment-741073586

**Comment by thomasstjerne** [comment]
It displays whatever comes from the info object:
<img width="816" alt="Screenshot at Dec 09 08-42-09" src="https://user-images.githubusercontent.com/1666484/101599970-f631d400-39fa-11eb-9ef9-30f659ebf63c.png">

**Comment by mdoering** [comment]
Yes, which is wrong. That map is just a convenience lookup to save lookup calls for referenceIDs.
The real list of reference IDs to show is in the taxon object itself
