### ISSUE TITLE
Taxon page titles do not include the taxon name

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/portal#96]
On taxon pages, the page title should be changed to include the taxon name. For example, this page has the title "Browse | COL":

https://www.catalogueoflife.org/data/taxon/58PXH

The title probably should be "Trifolium lupinaster L. | COL"

Having all of our taxon pages have the title "Browse | COL" might hurt our search engine rankings, and will make it harder to bookmark, share, and use the site.

**Comment by mdoering** [comment]
same for dataset details and maybe even the search.
A google search also changes its title based on the search term "search term | COL"

**Comment by thomasstjerne** [comment]
I have added title modification to the react components.However, this is happening on the client (in the browser). We dont serve pages dynamically, so this will probably only affect search results when accompanied by a site map.
