### ISSUE TITLE
News category links bad

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/portal#97]
If you follow the category link from the new you are taken to the home page, not to news filtered by the selected category:
From https://www.catalogueoflife.org/news/index
To https://www.catalogueoflife.org/category/partnerships

Either remove the news category completely or make the link work to show news items with only that category.

**Comment by mdoering** [comment]
see https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins

**Comment by chantalhuijbers** [comment]
@dhobern can you have a look at this?

**Comment by dhobern** [comment]
I downloaded the project from GitHub, built it on my system and ran it without hitting this issue, which I can see on the live site.

I don't think I have access to check what has happened on the server, but here is what I can see. The site builds the news/index.html page dynamically under _site, as well as a set of category folders and other folders named after components in the article date..  The generated HTML in the sidebar to select the categories or months included relative URLs of the form "/category/partnerships". Adding "/index" to the end fixed the problem when I tested it manually. I assume some URL rewriting on the main server. I have therefore changed the sidebar code to include that addition.

#f1cab9886fe32d60bfa206b211ab17bed64b802b

@mdoering @thomasstjerne Could one of you please push to production
